### ISSUE TITLE
crash: undefined method `[]=' for nil:NilClass (NoMethodError)

### ISSUE THREAD

**Issue by tmornini** [ruby-grape/grape-entity#166]
Hey guys. Updating to 0.4.6 or 0.4.7 crashes on the following code which has run unchanged since the 0.3.0 days. :-)

```
Grape::Entity.format_with :id do |entity|
                                entity.id unless entity.nil?
                              end
```

```
/Users/tmornini/.rbenv/versions/1.9.3-p551/lib/ruby/gems/1.9.1/gems/grape-entity-0.4.7/lib/grape_entity/entity.rb:243:in `format_with': undefined method `[]=' for nil:NilClass (NoMethodError)
	from /Users/tmornini/subledger/subledger/lib/subledger/domain/formatters.rb:1:in `<top (required)>'
	from /Users/tmornini/.rbenv/versions/1.9.3-p551/lib/ruby/1.9.1/rubygems/custom_require.rb:55:in `require'
	from /Users/tmornini/.rbenv/versions/1.9.3-p551/lib/ruby/1.9.1/rubygems/custom_require.rb:55:in `require'
	from /Users/tmornini/subledger/subledger/lib/subledger/domain.rb:94:in `<top (required)>'
	from /Users/tmornini/.rbenv/versions/1.9.3-p551/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
	from /Users/tmornini/.rbenv/versions/1.9.3-p551/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
	from /Users/tmornini/subledger/subledger/lib/subledger.rb:17:in `<top (required)>'
	from /Users/tmornini/.rbenv/versions/1.9.3-p551/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
	from /Users/tmornini/.rbenv/versions/1.9.3-p551/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
	from /Users/tmornini/.rbenv/versions/1.9.3-p551/lib/ruby/1.9.1/irb/init.rb:281:in `block in load_modules'
	from /Users/tmornini/.rbenv/versions/1.9.3-p551/lib/ruby/1.9.1/irb/init.rb:279:in `each'
	from /Users/tmornini/.rbenv/versions/1.9.3-p551/lib/ruby/1.9.1/irb/init.rb:279:in `load_modules'
	from /Users/tmornini/.rbenv/versions/1.9.3-p551/lib/ruby/1.9.1/irb/init.rb:20:in `setup'
	from /Users/tmornini/.rbenv/versions/1.9.3-p551/lib/ruby/1.9.1/irb.rb:53:in `start'
	from /Users/tmornini/.rbenv/versions/1.9.3-p551/bin/irb:12:in `<main>'
```

**Comment by marshall-lee** [comment]
@tmornini please provide an example how you use `:format_with` option.

**Comment by marshall-lee** [comment]
ah, sorry.

**Comment by marshall-lee** [comment]
@dblock

I bet it's caused by #134.

Defining global formatters on `Grape::Entity` is not documented and has no specs. However, I don't see anything harmful in this. What do you think?

**Comment by marshall-lee** [comment]
@tmornini 

As a quick fix I can propose you not to define global formatters on `Grape::Entity` but make a base class for all you entity classes and setup formatter in it.

As I said such possibility is not documented so if you think that it should exist lets discuss it.

**Comment by marshall-lee** [comment]
There's also an issue #161. It's about `exposures` but it propagates to `formatters` and other things too. It can bite someone who defines global `formatters` on `Grape::Entity` *after* creating a subclass from `Grape::Entity` — they simple won't get that formatter in a subclass.

**Comment by dblock** [comment]
@marshall-lee sounds like you have it all covered, do what you have to do

**Comment by tmornini** [comment]
@marshall-lee Like this?

```
class EntityBase < Grape::Entity
  format_with :id do |entity|
                    entity.id unless entity.nil?
                  end
end
```

**Comment by marshall-lee** [comment]
@tmornini yes.

Also i will fix it soon, so maybe you don't have to change your existing code if you just wait a bit :)

**Comment by tmornini** [comment]
@marshall-lee Even better! :-)

**Comment by marshall-lee** [comment]
@tmornini please try out 0.4.8

**Comment by tmornini** [comment]
@marshall-lee 0.4.8 has resolved our issue.

Thank you!
