### ISSUE TITLE
NoMethodError (undefined method `represent' for [...]) when using nested entities

### ISSUE THREAD

**Issue by gopeter** [ruby-grape/grape-entity#80]
I'm using Grape 0.7.0 and Grape-Entity 0.4.3 and get a `NoMethodError` when trying to nest entities:

```
  module Entities

    class Client < Grape::Entity
      expose :id
      expose :number
      expose :company
      expose :address1
      expose :address2
      expose :city
      expose :zip
      expose :country
      expose :tax
      expose :email
      expose :phone
      expose :web
      expose :contacts, using: API::Entities::Contact
    end

    class Contact < Grape::Entity
      expose :id
      expose :title
      expose :name
      expose :surname
      expose :department
      expose :email
      expose :phone
      expose :client_id
    end

  end
```

My route:

```
module Routes
  class Clients < Grape::API

    resource :clients do

      desc 'Get all clients'
      params do
        optional :ids, type: String, desc: 'Comma-separated list of IDs'
      end

      get do   # GET /api/v1/clients
        authenticate!

        clients = Client.all.order(:company)
        clients = clients.where(:id => params[:ids].split(',')) if params['ids']

        error! 'There are no clients', 404 unless clients.any?
        present clients, with: API::Entities::Client

      end

  end
end
```

Thats the full error log:

```
NoMethodError (undefined method `represent' for #<Class:0x00000104b425d0>):
  activerecord (4.1.1) lib/active_record/dynamic_matchers.rb:26:in `method_missing'
  grape-entity (0.4.3) lib/grape_entity/entity.rb:457:in `value_for'
  grape-entity (0.4.3) lib/grape_entity/entity.rb:397:in `block in serializable_hash'
  grape-entity (0.4.3) lib/grape_entity/entity.rb:395:in `each'
  grape-entity (0.4.3) lib/grape_entity/entity.rb:395:in `inject'
  grape-entity (0.4.3) lib/grape_entity/entity.rb:395:in `serializable_hash'
  activesupport (4.1.1) lib/active_support/core_ext/object/json.rb:140:in `block in as_json'
  activesupport (4.1.1) lib/active_support/core_ext/object/json.rb:140:in `map'
  activesupport (4.1.1) lib/active_support/core_ext/object/json.rb:140:in `as_json'
  activesupport (4.1.1) lib/active_support/json/encoding.rb:34:in `encode'
  activesupport (4.1.1) lib/active_support/json/encoding.rb:21:in `encode'
  activesupport (4.1.1) lib/active_support/core_ext/object/json.rb:37:in `to_json_with_active_support_encoder'
  grape (0.7.0) lib/grape/formatter/json.rb:6:in `call'
  grape (0.7.0) lib/grape/middleware/formatter.rb:33:in `block in after'
  grape (0.7.0) lib/grape/middleware/formatter.rb:32:in `collect'
  grape (0.7.0) lib/grape/middleware/formatter.rb:32:in `after'
  grape (0.7.0) lib/grape/middleware/base.rb:25:in `call!'
  grape (0.7.0) lib/grape/middleware/base.rb:18:in `call'
  grape (0.7.0) lib/grape/middleware/base.rb:24:in `call!'
  grape (0.7.0) lib/grape/middleware/base.rb:18:in `call'
  grape (0.7.0) lib/grape/middleware/error.rb:26:in `block in call!'
  grape (0.7.0) lib/grape/middleware/error.rb:25:in `catch'
  grape (0.7.0) lib/grape/middleware/error.rb:25:in `call!'
  grape (0.7.0) lib/grape/middleware/base.rb:18:in `call'
  newrelic-grape (1.3.1) lib/newrelic-grape/instrument.rb:19:in `block in call!'
  newrelic_rpm (3.8.1.221) lib/new_relic/agent/instrumentation/controller_instrumentation.rb:357:in `perform_action_with_newrelic_trace'
  newrelic-grape (1.3.1) lib/newrelic-grape/instrument.rb:18:in `call!'
  grape (0.7.0) lib/grape/middleware/base.rb:18:in `call'
  rack (1.5.2) lib/rack/head.rb:11:in `call'
  rack (1.5.2) lib/rack/builder.rb:138:in `call'
  grape (0.7.0) lib/grape/endpoint.rb:157:in `call!'
  grape (0.7.0) lib/grape/endpoint.rb:145:in `call'
  rack-mount (0.8.3) lib/rack/mount/route_set.rb:152:in `block in call'
  rack-mount (0.8.3) lib/rack/mount/code_generation.rb:96:in `block in recognize'
  rack-mount (0.8.3) lib/rack/mount/code_generation.rb:68:in `optimized_each'
  rack-mount (0.8.3) lib/rack/mount/code_generation.rb:95:in `recognize'
  rack-mount (0.8.3) lib/rack/mount/route_set.rb:141:in `call'
  grape (0.7.0) lib/grape/api.rb:537:in `call'
  grape (0.7.0) lib/grape/api.rb:44:in `call!'
  grape (0.7.0) lib/grape/api.rb:40:in `call'
  actionpack (4.1.1) lib/action_dispatch/journey/router.rb:71:in `block in call'
  actionpack (4.1.1) lib/action_dispatch/journey/router.rb:59:in `each'
  actionpack (4.1.1) lib/action_dispatch/journey/router.rb:59:in `call'
  actionpack (4.1.1) lib/action_dispatch/routing/route_set.rb:676:in `call'
  apartment (0.24.3) lib/apartment/reloader.rb:18:in `call'
  newrelic_rpm (3.8.1.221) lib/new_relic/rack/error_collector.rb:55:in `call'
  newrelic_rpm (3.8.1.221) lib/new_relic/rack/agent_hooks.rb:32:in `call'
  newrelic_rpm (3.8.1.221) lib/new_relic/rack/browser_monitoring.rb:27:in `call'
  rack-cors (0.2.9) lib/rack/cors.rb:54:in `call'
  apartment (0.24.3) lib/apartment/elevators/generic.rb:22:in `call'
  rack (1.5.2) lib/rack/etag.rb:23:in `call'
  rack (1.5.2) lib/rack/conditionalget.rb:25:in `call'
  rack (1.5.2) lib/rack/head.rb:11:in `call'
  actionpack (4.1.1) lib/action_dispatch/middleware/params_parser.rb:27:in `call'
  actionpack (4.1.1) lib/action_dispatch/middleware/flash.rb:254:in `call'
  rack (1.5.2) lib/rack/session/abstract/id.rb:225:in `context'
  rack (1.5.2) lib/rack/session/abstract/id.rb:220:in `call'
  actionpack (4.1.1) lib/action_dispatch/middleware/cookies.rb:560:in `call'
  activerecord (4.1.1) lib/active_record/query_cache.rb:36:in `call'
  activerecord (4.1.1) lib/active_record/connection_adapters/abstract/connection_pool.rb:621:in `call'
  activerecord (4.1.1) lib/active_record/migration.rb:380:in `call'
  actionpack (4.1.1) lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
  activesupport (4.1.1) lib/active_support/callbacks.rb:82:in `run_callbacks'
  actionpack (4.1.1) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
  actionpack (4.1.1) lib/action_dispatch/middleware/reloader.rb:73:in `call'
  actionpack (4.1.1) lib/action_dispatch/middleware/remote_ip.rb:76:in `call'
  actionpack (4.1.1) lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
  actionpack (4.1.1) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
  railties (4.1.1) lib/rails/rack/logger.rb:38:in `call_app'
  railties (4.1.1) lib/rails/rack/logger.rb:20:in `block in call'
  activesupport (4.1.1) lib/active_support/tagged_logging.rb:68:in `block in tagged'
  activesupport (4.1.1) lib/active_support/tagged_logging.rb:26:in `tagged'
  activesupport (4.1.1) lib/active_support/tagged_logging.rb:68:in `tagged'
  railties (4.1.1) lib/rails/rack/logger.rb:20:in `call'
  actionpack (4.1.1) lib/action_dispatch/middleware/request_id.rb:21:in `call'
  rack (1.5.2) lib/rack/methodoverride.rb:21:in `call'
  rack (1.5.2) lib/rack/runtime.rb:17:in `call'
  activesupport (4.1.1) lib/active_support/cache/strategy/local_cache_middleware.rb:26:in `call'
  rack (1.5.2) lib/rack/lock.rb:17:in `call'
  actionpack (4.1.1) lib/action_dispatch/middleware/static.rb:64:in `call'
  rack (1.5.2) lib/rack/sendfile.rb:112:in `call'
  railties (4.1.1) lib/rails/engine.rb:514:in `call'
  railties (4.1.1) lib/rails/application.rb:144:in `call'
  rack (1.5.2) lib/rack/content_length.rb:14:in `call'
  puma (2.8.2) lib/puma/server.rb:490:in `handle_request'
  puma (2.8.2) lib/puma/server.rb:361:in `process_client'
  puma (2.8.2) lib/puma/server.rb:254:in `block in run'
  puma (2.8.2) lib/puma/thread_pool.rb:92:in `call'
  puma (2.8.2) lib/puma/thread_pool.rb:92:in `block in spawn_thread'


  Rendered /Users/peter_goebel/.rvm/gems/ruby-2.1.1/gems/actionpack-4.1.1/lib/action_dispatch/middleware/templates/rescues/_source.erb (0.8ms)
  Rendered /Users/peter_goebel/.rvm/gems/ruby-2.1.1/gems/actionpack-4.1.1/lib/action_dispatch/middleware/templates/rescues/_trace.html.erb (1.4ms)
  Rendered /Users/peter_goebel/.rvm/gems/ruby-2.1.1/gems/actionpack-4.1.1/lib/action_dispatch/middleware/templates/rescues/_request_and_response.html.erb (1.3ms)
  Rendered /Users/peter_goebel/.rvm/gems/ruby-2.1.1/gems/actionpack-4.1.1/lib/action_dispatch/middleware/templates/rescues/diagnostics.erb within rescues/layout (17.1ms)
```

**Comment by X-Stranger** [comment]
Had the same issue with my application. It seems that order of Entity classes definition also counts. Before fix:
```
module API
  module Entities

    class List < Grape::Entity
      expose :id, :title, :description
      expose :things, using: Thing
    end

    class Thing < Grape::Entity
      expose :id, :description
    end

  end
end
```
Yes, I can fix this by moving entity definitions to the models, but I don't want to mix this code. The solution was quite easier, just changed definition order:
```
module API
  module Entities

    class Thing < Grape::Entity
      expose :id, :description
    end

    class List < Grape::Entity
      expose :id, :title, :description
      expose :things, using: Thing
    end

  end
end
```
Now it works. At least for me.

**Comment by TangMonk** [comment]
the order problem?!

but if I define the Entity in the ActiveRecord model? How Can I change the order?

**Comment by quentindecock** [comment]
Changing the order in which I define my entities fixed the issue.

**Comment by mwalkowiak** [comment]
That did the trick for me too...

**Comment by FrankFang** [comment]
@quentindecock  You got the point, I believe.

**Comment by phani627** [comment]
Changing Order fixed my issue
